---
- name: Deploy Looper Host
  hosts: all
  vars:
    - start_: "{{ start | default(false) }}"
  tasks:
  - name: Check for cmake
    ansible.builtin.stat:
      path: /usr/bin/cmake
    register: cmake_installed

  - name: Install Packages
    become: yes
    apt:
      name:
        - cmake
    when: not cmake_installed.stat.exists 

  - name: Create Directory
    become: yes
    ansible.builtin.file:
      path: /opt/looper
      state: directory 
      mode: '0755'

  - name: Change Ownership
    become: yes
    ansible.builtin.command:
      cmd: chown -R patch /opt/looper
      
  - name: Clone Looper Host repo
    ansible.builtin.git:
      repo: git@github.com:jsomwaru/looper-host.git
      dest: /opt/looper/looper-host
      accept_hostkey: yes  
      version: tc-v0.1

  - name: Cmake Lopper Host
    ansible.builtin.command:
      chdir: /opt/looper/looper-host
      cmd: cmake .

  - name: Check for prebuilt looper host
    ansible.builtin.stat:
      path: /opt/looper/looper-host/looper_host
    register: prebuilt

    # Make on pisound does detect differnces very well
    # and sometimes does not build a new executable
    # even is there are changes
  - name: "Make clean"
    ansible.builtin.command:
      chdir: /opt/looper/looper-host/
      cmd: make clean
    when: prebuilt.stat.exists

  - name: Build Looper Host
    ansible.builtin.command:
      chdir: /opt/looper/looper-host
      cmd: make

  - name: Start Looper Host
    ansible.builtin.command:
      chdir: /opt/looper/looper-host
      cmd: tmux new-session -d -s looper_host './looper_host'
    when: start_ | bool
